### ISSUE TITLE
Getting a TypeError

### ISSUE THREAD

**Issue by iethan** [jomcgrath2/Update-Fusion#1]
When I Update Fusion Table, I get the following error:

TypeError: Cannot call method "getRowIndex" of null. (line 93)

Is this a known issue?

**Comment by jomcgrath2** [comment]
I am not sure which version your using but it sounds like the data range may not be set.  Try using the new button that appears in the toolbar to set the range of the data to be sent to fusion.  If this doesn't help let me know.
